hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
zuul:
  routes:
    product: /myProduct/**
    myProduct:
       path: /myProduct/**
       serviceId: product
  ignored-patterns: #排除某些路由
#    - /product/product/list
#    - /myProduct/product/list
#    - /**/list
  sensitive-headers:
  ratelimit:
    enabled: true
    repository: redis
    behind-proxy: true
    policy-list:
      myProduct:
        - limit: 1
          quota: 1000
          refreshInterval: 10
          type:
            - user
            - origin
            - url
    default-policy-list:
      - limit: 10
        quota: 1000
        refreshInterval: 10
        type:
          - user
          - origin
          - url
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  redis:
    host: localhost
    port: 6379


