spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Aa412629
    url: jdbc:mysql://47.96.18.57:3306/springCloud_Sell?characterEncoding=utf-8&useSSL=false
    dbcp2:
          validation-query: SELECT 1
          test-on-borrow: true
#          test-on-return: false
#          test-while-idle: true
  jpa:
      show-sql: true
product:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
server:
  port: 1201
env:
  dev
girl:
  name: wyl
  age: 25
