spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Aa412629
    url: jdbc:mysql://47.96.18.57:3306/springCloud_Sell?characterEncoding=utf-8&useSSL=false
    dbcp2:
      validation-query: SELECT 1
      test-on-borrow: true
#      test-on-return: false
#      test-while-idle: true
  jpa:
      show-sql: true
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    #默认就是json类型？ 一下当输出到rabbitmq后会变成json类型,而不会是字节码
#  cloud:
#    stream:
#      bindings:
#        myMessage:
#          content-type: application/json
eureka:
  client:
    service-url:
      defaultUrl: http://server1:8761/eureka
